name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
        python -m pip install --require-hashes -r requirements.txt
    - name: pre-commit
      run: |
        pre-commit run --all-files
    - name: Run Tests
      run: |
        python manage.py test
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check
